package com.dogstories.Models

enum class Type {
    PRINT,
    ASSIGN_LOCAL,
    CREATE_VAR,
    ASSIGN_GLOBAL,
    USE_METHOD,
    USE_METHOD_PARAMS,
    ASSIGN_ARR,
    ASSIGN_GLOBAL_ARR,
    ASSIGN_ARR_NUM,
    ASSIGN_GLOBAL_ARR_NUM,
    INCREASE_VAR_BY_VAL,
    DECREASE_VAR_BY_VAL,
    INCREASE_GLOBAL_BY_VAL,
    DECREASE_GLOBAL_BY_VAL
}